version: '3.9'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    environment:
      - FLASK_DEBUG=true
    depends_on:
      - redis
    command: flask run --host=0.0.0.0 --port=5001

  redis:
    image: "redis:alpine"
